<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.hstore</groupId>
        <artifactId>hstore-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>hstore-db</artifactId>
    <name>HStore Database</name>

    <dependencies>
        <dependency>
            <groupId>io.hstore</groupId>
            <artifactId>hstore-engine</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-testCompile</id>
                        <configuration>
                            <compilerArgs combine.children="append">
                                <arg>--add-modules</arg>
                                <arg>jdk.httpserver</arg>
                                <arg>--add-reads</arg>
                                <arg>io.hstore.db=jdk.httpserver</arg>
                            </compilerArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>--add-modules jdk.httpserver --add-reads io.hstore.db=jdk.httpserver</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
