CREATE NODE TYPE Patient (name STRING INDEXED REQUIRED, age INT INDEXED, city STRING);
CREATE NODE TYPE Provider (name STRING INDEXED REQUIRED, specialty STRING INDEXED);
CREATE NODE TYPE Drug (name STRING INDEXED REQUIRED, class STRING INDEXED);
CREATE NODE TYPE Pharmacy (name STRING INDEXED REQUIRED);
CREATE SET EDGE TYPE Prescription (cost FLOAT INDEXED, refills INT) ROLES (patient, prescriber, drug, pharmacy);
CREATE SET EDGE TYPE Claim (amount FLOAT INDEXED, status STRING INDEXED) ROLES (patient, provider, drug, pharmacy);
CREATE ORDERED EDGE TYPE CarePathway (condition STRING INDEXED);
CREATE SET EDGE TYPE Investigation (reason STRING) ROLES (subject, investigator, witness);

INSERT NODE Patient 'asha-rao' {name: 'Asha Rao', age: 60, city: 'Boston'} AS $asha_rao;
INSERT NODE Patient 'ben-carter' {name: 'Ben Carter', age: 69, city: 'Austin'} AS $ben_carter;
INSERT NODE Patient 'chen-wei' {name: 'Chen Wei', age: 28, city: 'Seattle'} AS $chen_wei;
INSERT NODE Patient 'dara-okafor' {name: 'Dara Okafor', age: 31, city: 'Chicago'} AS $dara_okafor;
INSERT NODE Patient 'elena-petrova' {name: 'Elena Petrova', age: 26, city: 'Seattle'} AS $elena_petrova;
INSERT NODE Patient 'farid-haddad' {name: 'Farid Haddad', age: 46, city: 'Austin'} AS $farid_haddad;
INSERT NODE Patient 'grace-kim' {name: 'Grace Kim', age: 30, city: 'Denver'} AS $grace_kim;
INSERT NODE Patient 'hugo-laurent' {name: 'Hugo Laurent', age: 72, city: 'Austin'} AS $hugo_laurent;
INSERT NODE Patient 'ines-duarte' {name: 'Ines Duarte', age: 49, city: 'Austin'} AS $ines_duarte;
INSERT NODE Patient 'jonas-berg' {name: 'Jonas Berg', age: 73, city: 'Austin'} AS $jonas_berg;
INSERT NODE Patient 'kavya-iyer' {name: 'Kavya Iyer', age: 34, city: 'Boston'} AS $kavya_iyer;
INSERT NODE Patient 'liam-oneil' {name: 'Liam O''Neil', age: 26, city: 'Seattle'} AS $liam_oneil;
INSERT NODE Patient 'mei-tanaka' {name: 'Mei Tanaka', age: 69, city: 'Austin'} AS $mei_tanaka;
INSERT NODE Patient 'noah-fischer' {name: 'Noah Fischer', age: 47, city: 'Austin'} AS $noah_fischer;
INSERT NODE Patient 'olivia-brooks' {name: 'Olivia Brooks', age: 36, city: 'Chicago'} AS $olivia_brooks;
INSERT NODE Patient 'pedro-alvarez' {name: 'Pedro Alvarez', age: 72, city: 'Boston'} AS $pedro_alvarez;
INSERT NODE Patient 'quinn-murphy' {name: 'Quinn Murphy', age: 88, city: 'Austin'} AS $quinn_murphy;
INSERT NODE Patient 'rosa-bianchi' {name: 'Rosa Bianchi', age: 58, city: 'Seattle'} AS $rosa_bianchi;
INSERT NODE Patient 'sami-nasser' {name: 'Sami Nasser', age: 42, city: 'Austin'} AS $sami_nasser;
INSERT NODE Patient 'tara-singh' {name: 'Tara Singh', age: 43, city: 'Chicago'} AS $tara_singh;
INSERT NODE Patient 'uma-desai' {name: 'Uma Desai', age: 31, city: 'Seattle'} AS $uma_desai;
INSERT NODE Patient 'victor-hugo' {name: 'Victor Hugo', age: 27, city: 'Seattle'} AS $victor_hugo;
INSERT NODE Patient 'wen-li' {name: 'Wen Li', age: 26, city: 'Seattle'} AS $wen_li;
INSERT NODE Patient 'yara-haddad' {name: 'Yara Haddad', age: 45, city: 'Denver'} AS $yara_haddad;
INSERT NODE Provider 'dr-ada-park' {name: 'Dr. Ada Park', specialty: 'cardiology'} AS $dr_ada_park;
INSERT NODE Provider 'dr-ben-osei' {name: 'Dr. Ben Osei', specialty: 'oncology'} AS $dr_ben_osei;
INSERT NODE Provider 'dr-clara-voss' {name: 'Dr. Clara Voss', specialty: 'general practice'} AS $dr_clara_voss;
INSERT NODE Provider 'dr-dev-mehta' {name: 'Dr. Dev Mehta', specialty: 'endocrinology'} AS $dr_dev_mehta;
INSERT NODE Provider 'dr-eva-lund' {name: 'Dr. Eva Lund', specialty: 'neurology'} AS $dr_eva_lund;
INSERT NODE Provider 'dr-femi-ade' {name: 'Dr. Femi Ade', specialty: 'general practice'} AS $dr_femi_ade;
INSERT NODE Provider 'dr-gil-moran' {name: 'Dr. Gil Moran', specialty: 'orthopedics'} AS $dr_gil_moran;
INSERT NODE Provider 'dr-hana-sato' {name: 'Dr. Hana Sato', specialty: 'psychiatry'} AS $dr_hana_sato;
INSERT NODE Provider 'dr-ivan-kral' {name: 'Dr. Ivan Kral', specialty: 'cardiology'} AS $dr_ivan_kral;
INSERT NODE Provider 'dr-jia-chen' {name: 'Dr. Jia Chen', specialty: 'pulmonology'} AS $dr_jia_chen;
INSERT NODE Drug 'atorvastatin' {name: 'Atorvastatin', class: 'statin'} AS $atorvastatin;
INSERT NODE Drug 'metformin' {name: 'Metformin', class: 'biguanide'} AS $metformin;
INSERT NODE Drug 'lisinopril' {name: 'Lisinopril', class: 'ACE inhibitor'} AS $lisinopril;
INSERT NODE Drug 'sertraline' {name: 'Sertraline', class: 'SSRI'} AS $sertraline;
INSERT NODE Drug 'oxycodone' {name: 'Oxycodone', class: 'opioid'} AS $oxycodone;
INSERT NODE Drug 'albuterol' {name: 'Albuterol', class: 'bronchodilator'} AS $albuterol;
INSERT NODE Drug 'insulin-glargine' {name: 'Insulin glargine', class: 'insulin'} AS $insulin_glargine;
INSERT NODE Drug 'warfarin' {name: 'Warfarin', class: 'anticoagulant'} AS $warfarin;
INSERT NODE Pharmacy 'northside-pharmacy' {name: 'Northside Pharmacy'} AS $northside_pharmacy;
INSERT NODE Pharmacy 'harbor-rx' {name: 'Harbor Rx'} AS $harbor_rx;
INSERT NODE Pharmacy 'central-apothecary' {name: 'Central Apothecary'} AS $central_apothecary;
INSERT NODE Pharmacy 'lakeview-drugs' {name: 'Lakeview Drugs'} AS $lakeview_drugs;

INSERT EDGE Prescription {cost: 199.83, refills: 3} MEMBERS ($victor_hugo AS patient, $dr_ivan_kral AS prescriber, $insulin_glargine AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 295.99, refills: 1} MEMBERS ($liam_oneil AS patient, $dr_eva_lund AS prescriber, $sertraline AS drug, $harbor_rx AS pharmacy);
INSERT EDGE Prescription {cost: 368.56, refills: 5} MEMBERS ($chen_wei AS patient, $dr_jia_chen AS prescriber, $oxycodone AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 218.92, refills: 1} MEMBERS ($olivia_brooks AS patient, $dr_eva_lund AS prescriber, $metformin AS drug, $northside_pharmacy AS pharmacy);
INSERT EDGE Prescription {cost: 24.15, refills: 5} MEMBERS ($kavya_iyer AS patient, $dr_clara_voss AS prescriber, $warfarin AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 294.46, refills: 4} MEMBERS ($chen_wei AS patient, $dr_ivan_kral AS prescriber, $albuterol AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 354.07, refills: 2} MEMBERS ($pedro_alvarez AS patient, $dr_jia_chen AS prescriber, $warfarin AS drug, $northside_pharmacy AS pharmacy);
INSERT EDGE Prescription {cost: 274.62, refills: 5} MEMBERS ($pedro_alvarez AS patient, $dr_ben_osei AS prescriber, $atorvastatin AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 17.3, refills: 3} MEMBERS ($olivia_brooks AS patient, $dr_eva_lund AS prescriber, $insulin_glargine AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 32.29, refills: 2} MEMBERS ($liam_oneil AS patient, $dr_clara_voss AS prescriber, $metformin AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 385.73, refills: 3} MEMBERS ($elena_petrova AS patient, $dr_dev_mehta AS prescriber, $insulin_glargine AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 234.37, refills: 1} MEMBERS ($chen_wei AS patient, $dr_clara_voss AS prescriber, $warfarin AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 414.42, refills: 5} MEMBERS ($noah_fischer AS patient, $dr_ivan_kral AS prescriber, $oxycodone AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 80.6, refills: 1} MEMBERS ($mei_tanaka AS patient, $dr_dev_mehta AS prescriber, $lisinopril AS drug, $northside_pharmacy AS pharmacy);
INSERT EDGE Prescription {cost: 350.41, refills: 1} MEMBERS ($victor_hugo AS patient, $dr_dev_mehta AS prescriber, $atorvastatin AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 180.61, refills: 2} MEMBERS ($ines_duarte AS patient, $dr_eva_lund AS prescriber, $atorvastatin AS drug, $harbor_rx AS pharmacy);
INSERT EDGE Prescription {cost: 292.48, refills: 4} MEMBERS ($tara_singh AS patient, $dr_jia_chen AS prescriber, $albuterol AS drug, $harbor_rx AS pharmacy);
INSERT EDGE Prescription {cost: 172.0, refills: 3} MEMBERS ($tara_singh AS patient, $dr_ada_park AS prescriber, $warfarin AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 86.53, refills: 1} MEMBERS ($dara_okafor AS patient, $dr_hana_sato AS prescriber, $insulin_glargine AS drug, $northside_pharmacy AS pharmacy);
INSERT EDGE Prescription {cost: 255.5, refills: 0} MEMBERS ($olivia_brooks AS patient, $dr_clara_voss AS prescriber, $metformin AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 398.97, refills: 4} MEMBERS ($asha_rao AS patient, $dr_jia_chen AS prescriber, $lisinopril AS drug, $northside_pharmacy AS pharmacy);
INSERT EDGE Prescription {cost: 69.2, refills: 2} MEMBERS ($asha_rao AS patient, $dr_ben_osei AS prescriber, $sertraline AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 58.61, refills: 3} MEMBERS ($liam_oneil AS patient, $dr_jia_chen AS prescriber, $albuterol AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 43.38, refills: 0} MEMBERS ($olivia_brooks AS patient, $dr_hana_sato AS prescriber, $warfarin AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 349.49, refills: 1} MEMBERS ($yara_haddad AS patient, $dr_femi_ade AS prescriber, $oxycodone AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 68.4, refills: 4} MEMBERS ($quinn_murphy AS patient, $dr_ada_park AS prescriber, $sertraline AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 294.83, refills: 2} MEMBERS ($asha_rao AS patient, $dr_ivan_kral AS prescriber, $oxycodone AS drug, $northside_pharmacy AS pharmacy);
INSERT EDGE Prescription {cost: 326.04, refills: 4} MEMBERS ($quinn_murphy AS patient, $dr_femi_ade AS prescriber, $lisinopril AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 260.65, refills: 1} MEMBERS ($rosa_bianchi AS patient, $dr_ivan_kral AS prescriber, $albuterol AS drug, $harbor_rx AS pharmacy);
INSERT EDGE Prescription {cost: 221.27, refills: 2} MEMBERS ($hugo_laurent AS patient, $dr_gil_moran AS prescriber, $sertraline AS drug, $harbor_rx AS pharmacy);
INSERT EDGE Prescription {cost: 202.56, refills: 1} MEMBERS ($yara_haddad AS patient, $dr_ada_park AS prescriber, $atorvastatin AS drug, $central_apothecary AS pharmacy);
INSERT EDGE Prescription {cost: 341.13, refills: 5} MEMBERS ($wen_li AS patient, $dr_jia_chen AS prescriber, $albuterol AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 50.09, refills: 3} MEMBERS ($liam_oneil AS patient, $dr_femi_ade AS prescriber, $metformin AS drug, $harbor_rx AS pharmacy);
INSERT EDGE Prescription {cost: 265.12, refills: 4} MEMBERS ($grace_kim AS patient, $dr_femi_ade AS prescriber, $sertraline AS drug, $lakeview_drugs AS pharmacy);
INSERT EDGE Prescription {cost: 351.88, refills: 0} MEMBERS ($asha_rao AS patient, $dr_hana_sato AS prescriber, $albuterol AS drug, $northside_pharmacy AS pharmacy);
INSERT EDGE Prescription {cost: 186.78, refills: 5} MEMBERS ($mei_tanaka AS patient, $dr_dev_mehta AS prescriber, $warfarin AS drug, $harbor_rx AS pharmacy);
INSERT EDGE Claim {amount: 9281.8, status: 'flagged'} MEMBERS ($kavya_iyer AS patient, $dr_ben_osei AS provider WEIGHT 0.88, $lakeview_drugs AS pharmacy) AS $claim_0;
INSERT EDGE Claim {amount: 7915.33, status: 'pending'} MEMBERS ($yara_haddad AS patient, $dr_clara_voss AS provider WEIGHT 0.5, $lisinopril AS drug) AS $claim_1;
INSERT EDGE Claim {amount: 1578.59, status: 'paid'} MEMBERS ($elena_petrova AS patient, $dr_jia_chen AS provider WEIGHT 0.9) AS $claim_2;
INSERT EDGE Claim {amount: 5188.9, status: 'paid'} MEMBERS ($rosa_bianchi AS patient, $dr_clara_voss AS provider WEIGHT 0.41) AS $claim_3;
INSERT EDGE Claim {amount: 4941.32, status: 'paid'} MEMBERS ($elena_petrova AS patient, $dr_gil_moran AS provider WEIGHT 0.99, $sertraline AS drug, $harbor_rx AS pharmacy) AS $claim_4;
INSERT EDGE Claim {amount: 6512.5, status: 'pending'} MEMBERS ($sami_nasser AS patient, $dr_femi_ade AS provider WEIGHT 0.56, $lisinopril AS drug, $central_apothecary AS pharmacy) AS $claim_5;
INSERT EDGE Claim {amount: 5032.73, status: 'denied'} MEMBERS ($quinn_murphy AS patient, $dr_gil_moran AS provider WEIGHT 0.9, $harbor_rx AS pharmacy) AS $claim_6;
INSERT EDGE Claim {amount: 6090.05, status: 'pending'} MEMBERS ($olivia_brooks AS patient, $dr_clara_voss AS provider WEIGHT 0.77, $harbor_rx AS pharmacy) AS $claim_7;
INSERT EDGE Claim {amount: 8662.64, status: 'paid'} MEMBERS ($dara_okafor AS patient, $dr_ivan_kral AS provider WEIGHT 0.44, $warfarin AS drug) AS $claim_8;
INSERT EDGE Claim {amount: 331.41, status: 'denied'} MEMBERS ($ben_carter AS patient, $dr_dev_mehta AS provider WEIGHT 0.51, $metformin AS drug) AS $claim_9;
INSERT EDGE Claim {amount: 6807.2, status: 'paid'} MEMBERS ($chen_wei AS patient, $dr_hana_sato AS provider WEIGHT 0.6) AS $claim_10;
INSERT EDGE Claim {amount: 9047.92, status: 'paid'} MEMBERS ($olivia_brooks AS patient, $dr_ivan_kral AS provider WEIGHT 0.72, $sertraline AS drug) AS $claim_11;
INSERT EDGE Claim {amount: 772.2, status: 'pending'} MEMBERS ($grace_kim AS patient, $dr_hana_sato AS provider WEIGHT 0.48, $warfarin AS drug, $harbor_rx AS pharmacy) AS $claim_12;
INSERT EDGE Claim {amount: 2525.27, status: 'paid'} MEMBERS ($victor_hugo AS patient, $dr_eva_lund AS provider WEIGHT 0.87, $central_apothecary AS pharmacy) AS $claim_13;
INSERT EDGE Claim {amount: 9701.35, status: 'paid'} MEMBERS ($elena_petrova AS patient, $dr_hana_sato AS provider WEIGHT 0.53, $lakeview_drugs AS pharmacy) AS $claim_14;
INSERT EDGE Claim {amount: 1966.55, status: 'pending'} MEMBERS ($hugo_laurent AS patient, $dr_clara_voss AS provider WEIGHT 0.82) AS $claim_15;
INSERT EDGE Claim {amount: 3803.52, status: 'paid'} MEMBERS ($kavya_iyer AS patient, $dr_ben_osei AS provider WEIGHT 0.83, $warfarin AS drug) AS $claim_16;
INSERT EDGE Claim {amount: 878.76, status: 'paid'} MEMBERS ($quinn_murphy AS patient, $dr_jia_chen AS provider WEIGHT 0.58, $harbor_rx AS pharmacy) AS $claim_17;
INSERT EDGE Claim {amount: 8036.86, status: 'flagged'} MEMBERS ($ines_duarte AS patient, $dr_ada_park AS provider WEIGHT 0.94, $lisinopril AS drug) AS $claim_18;
INSERT EDGE Claim {amount: 3245.45, status: 'flagged'} MEMBERS ($ines_duarte AS patient, $dr_gil_moran AS provider WEIGHT 0.49) AS $claim_19;
INSERT EDGE Claim {amount: 922.63, status: 'flagged'} MEMBERS ($ines_duarte AS patient, $dr_ada_park AS provider WEIGHT 0.88, $metformin AS drug, $northside_pharmacy AS pharmacy) AS $claim_20;
INSERT EDGE Claim {amount: 172.46, status: 'pending'} MEMBERS ($ines_duarte AS patient, $dr_ben_osei AS provider WEIGHT 0.76, $oxycodone AS drug) AS $claim_21;
INSERT EDGE Claim {amount: 9500.13, status: 'paid'} MEMBERS ($rosa_bianchi AS patient, $dr_gil_moran AS provider WEIGHT 0.96, $lisinopril AS drug, $harbor_rx AS pharmacy) AS $claim_22;
INSERT EDGE Claim {amount: 7457.51, status: 'denied'} MEMBERS ($ines_duarte AS patient, $dr_ada_park AS provider WEIGHT 0.51) AS $claim_23;
INSERT EDGE Claim {amount: 419.89, status: 'paid'} MEMBERS ($jonas_berg AS patient, $dr_hana_sato AS provider WEIGHT 0.7, $albuterol AS drug) AS $claim_24;
INSERT EDGE Claim {amount: 6472.04, status: 'paid'} MEMBERS ($asha_rao AS patient, $dr_ivan_kral AS provider WEIGHT 0.73, $warfarin AS drug, $lakeview_drugs AS pharmacy) AS $claim_25;
INSERT EDGE Claim {amount: 6758.6, status: 'paid'} MEMBERS ($uma_desai AS patient, $dr_gil_moran AS provider WEIGHT 0.79, $insulin_glargine AS drug) AS $claim_26;
INSERT EDGE Claim {amount: 4001.76, status: 'paid'} MEMBERS ($hugo_laurent AS patient, $dr_femi_ade AS provider WEIGHT 0.52) AS $claim_27;

INSERT EDGE CarePathway {condition: 'atrial fibrillation'} MEMBERS ($uma_desai, $dr_ada_park, $dr_clara_voss, $dr_jia_chen, $dr_hana_sato);
INSERT EDGE CarePathway {condition: 'asthma'} MEMBERS ($victor_hugo, $dr_gil_moran, $dr_clara_voss, $dr_ada_park, $dr_hana_sato);
INSERT EDGE CarePathway {condition: 'type 2 diabetes'} MEMBERS ($farid_haddad, $dr_eva_lund, $dr_dev_mehta, $dr_jia_chen, $dr_ada_park, $dr_ivan_kral);
INSERT EDGE CarePathway {condition: 'depression'} MEMBERS ($kavya_iyer, $dr_hana_sato, $dr_ada_park, $dr_eva_lund, $dr_clara_voss);
INSERT EDGE CarePathway {condition: 'type 2 diabetes'} MEMBERS ($liam_oneil, $dr_dev_mehta, $dr_ada_park, $dr_eva_lund, $dr_ben_osei);
INSERT EDGE CarePathway {condition: 'chronic back pain'} MEMBERS ($pedro_alvarez, $dr_femi_ade, $dr_gil_moran, $dr_ben_osei);
INSERT EDGE CarePathway {condition: 'type 2 diabetes'} MEMBERS ($chen_wei, $dr_dev_mehta, $dr_jia_chen, $dr_ada_park, $dr_hana_sato, $dr_clara_voss);
INSERT EDGE CarePathway {condition: 'chronic back pain'} MEMBERS ($jonas_berg, $dr_jia_chen, $dr_ada_park, $dr_gil_moran, $dr_ivan_kral);
INSERT EDGE CarePathway {condition: 'asthma'} MEMBERS ($tara_singh, $dr_dev_mehta, $dr_ben_osei, $dr_clara_voss, $dr_femi_ade, $dr_gil_moran);

INSERT EDGE Investigation {reason: 'duplicate billing pattern'} MEMBERS ($claim_0 AS subject, $claim_6 AS subject, $claim_9 AS subject, $dr_clara_voss AS investigator, $central_apothecary AS witness);
INSERT EDGE Investigation {reason: 'upcoding across visits'} MEMBERS ($claim_18 AS subject, $claim_19 AS subject, $claim_20 AS subject, $dr_clara_voss AS investigator, $lakeview_drugs AS witness);
INSERT EDGE Investigation {reason: 'opioid prescribing outlier'} MEMBERS ($claim_4 AS subject, $claim_6 AS subject, $claim_19 AS subject, $dr_clara_voss AS investigator, $harbor_rx AS witness);
