<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.hstore</groupId>
        <artifactId>hstore-parent</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>hstore-benchmarks</artifactId>
    <name>HStore Benchmarks</name>

    <properties>
        <hypergraphdb.version>1.4-99485a1</hypergraphdb.version>
        <je.version>5.0.73</je.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.hstore</groupId>
            <artifactId>hstore-db</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hypergraphdb</groupId>
            <artifactId>hgdb</artifactId>
            <version>${hypergraphdb.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hypergraphdb</groupId>
            <artifactId>hgbdbje</artifactId>
            <version>${hypergraphdb.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sleepycat</groupId>
            <artifactId>je</artifactId>
            <version>${je.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.9.0</version>
                <executions>
                    <execution>
                        <id>classpath</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-classpath</goal>
                        </goals>
                        <configuration>
                            <outputFile>${project.build.directory}/classpath.txt</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
